//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Art_Comment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Art_Comment()
        {
            this.Art_Comment1 = new HashSet<Art_Comment>();
            this.likes_art_comment = new HashSet<likes_art_comment>();
        }
    
        public int id { get; set; }
        public int users_id { get; set; }
        public int article_id { get; set; }
        public string content { get; set; }
        public Nullable<int> parent_comment_id { get; set; }
        public Nullable<int> likes_num { get; set; }
        public Nullable<System.DateTime> creat_time { get; set; }
    
        public virtual Articles Articles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Art_Comment> Art_Comment1 { get; set; }
        public virtual Art_Comment Art_Comment2 { get; set; }
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<likes_art_comment> likes_art_comment { get; set; }
    }
}
