//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LinxinaccessEntities : DbContext
    {
        public LinxinaccessEntities()
            : base("name=LinxinaccessEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Answer_Comment> Answer_Comment { get; set; }
        public virtual DbSet<Answers> Answers { get; set; }
        public virtual DbSet<Art_Comment> Art_Comment { get; set; }
        public virtual DbSet<Articles> Articles { get; set; }
        public virtual DbSet<Col_ans> Col_ans { get; set; }
        public virtual DbSet<Col_art> Col_art { get; set; }
        public virtual DbSet<Col_news> Col_news { get; set; }
        public virtual DbSet<Col_sci> Col_sci { get; set; }
        public virtual DbSet<Collects> Collects { get; set; }
        public virtual DbSet<likes_ans> likes_ans { get; set; }
        public virtual DbSet<likes_ans_comment> likes_ans_comment { get; set; }
        public virtual DbSet<likes_art> likes_art { get; set; }
        public virtual DbSet<likes_art_comment> likes_art_comment { get; set; }
        public virtual DbSet<likes_news> likes_news { get; set; }
        public virtual DbSet<likes_news_comment> likes_news_comment { get; set; }
        public virtual DbSet<likes_sci> likes_sci { get; set; }
        public virtual DbSet<likes_sci_comment> likes_sci_comment { get; set; }
        public virtual DbSet<likes_video_comment> likes_video_comment { get; set; }
        public virtual DbSet<News_Comment> News_Comment { get; set; }
        public virtual DbSet<Psy_news> Psy_news { get; set; }
        public virtual DbSet<Psy_videos> Psy_videos { get; set; }
        public virtual DbSet<Questions> Questions { get; set; }
        public virtual DbSet<Sci_articles> Sci_articles { get; set; }
        public virtual DbSet<Sci_Comment> Sci_Comment { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<Videos_Comment> Videos_Comment { get; set; }
    }
}
