//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Psy_news
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Psy_news()
        {
            this.Col_news = new HashSet<Col_news>();
            this.likes_news = new HashSet<likes_news>();
            this.News_Comment = new HashSet<News_Comment>();
        }
    
        public int id { get; set; }
        public string title { get; set; }
        public string content { get; set; }
        public string origin { get; set; }
        public string author { get; set; }
        public Nullable<int> likes_num { get; set; }
        public Nullable<int> comment_num { get; set; }
        public Nullable<int> views_num { get; set; }
        public Nullable<System.DateTime> creat_time { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Col_news> Col_news { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<likes_news> likes_news { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<News_Comment> News_Comment { get; set; }
    }
}
