//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sci_articles
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sci_articles()
        {
            this.Col_sci = new HashSet<Col_sci>();
            this.likes_sci = new HashSet<likes_sci>();
            this.Sci_Comment = new HashSet<Sci_Comment>();
        }
    
        public int id { get; set; }
        public string title { get; set; }
        public string content { get; set; }
        public string origin { get; set; }
        public string author { get; set; }
        public Nullable<int> likes_num { get; set; }
        public Nullable<int> comment_num { get; set; }
        public Nullable<int> views_num { get; set; }
        public Nullable<System.DateTime> creat_time { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Col_sci> Col_sci { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<likes_sci> likes_sci { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sci_Comment> Sci_Comment { get; set; }
    }
}
